{
 "title": "prometheus-net",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "instance", "label": "instance", "query": "system_runtime_cpu_usage" }
  ]
 },
 "panels": [
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% CPU consumption",
   "type": "timeseries",
   "description": "The percentage of available CPU resources consumed.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{instance=~\"gameserver:8001|hiveserver:8081|matchserver:9001\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% CPU Load",
   "type": "timeseries",
   "description": "The percentage of available CPU resources consumed.",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Current Application Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Instance % CPU consumption",
   "type": "stat",
   "description": "The percentage of available CPU resources consumed.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__interval]) / process_cpu_count{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% Memory consumption",
   "type": "stat",
   "description": "The percentage of available memory resources consumed.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"$instance\"} / dotnet_gc_memory_total_available_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "% Paused time",
   "type": "stat",
   "description": "The percentage of time that the application was paused to allow the garbage collector to run.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Thread pool queue length",
   "type": "stat",
   "description": "The average length of the thread pool's work queue. Values greater than 0 indicate a problem.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_threadpool_queue_length_sum{instance=\"$instance\"}[$__rate_interval]))  / \nsum(rate(dotnet_threadpool_queue_length_count{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Exceptions/ sec",
   "type": "stat",
   "description": "The rate of exceptions being thrown per second",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_exceptions_total{instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "HTTP Requests Per Interval",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "The duration of HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Server",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=~\"hiveserver:8081|gameserver:8001|matchserver:9001\"}[$__rate_interval])) by (instance)\r\n",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Memory / Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{instance=\"$instance\"}",
     "legendFormat": "# bytes (in physical memory)"
    },
    {
     "expr": "dotnet_gc_memory_total_available_bytes{instance=\"$instance\"}",
     "legendFormat": "Total bytes available (memory limit)"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Number of GC collections/ sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_collection_count_total{instance=\"$instance\"}[$__interval])) by (gc_generation, gc_reason)",
     "legendFormat": "gen {{gc_generation}}: {{gc_reason}}"
    }
   ]
  },
  {
   "title": "GC CPU + pause ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "dotnet_gc_cpu_ratio{instance=\"$instance\"}",
     "legendFormat": "GC CPU %"
    },
    {
     "expr": "dotnet_gc_pause_ratio{instance=\"$instance\"}",
     "legendFormat": "GC Pause %"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dotnet_gc_heap_size_bytes{instance=\"$instance\"}",
     "legendFormat": "gen {{gc_generation}}"
    }
   ]
  },
  {
   "title": "Bytes allocated (by heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_gc_allocated_bytes_total{instance=\"$instance\"}[$__interval])) by (gc_heap)",
     "legendFormat": "Alloc bytes {{gc_heap}}"
    }
   ]
  },
  { "title": "Thread pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Thread pool queue length",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (le) (increase(dotnet_threadpool_queue_length_bucket{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Num thread pool threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_threadpool_num_threads{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Num thread timers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_threadpool_timer_count{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}