{
 "title": "Omok API Game Server",
 "description": "오목 api server 모니터링 (Game, Hive, Match)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU 사용량(%)",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "누적 CPU 사용률",
   "type": "timeseries",
   "description": "누적 CPU  사용률 (4K=400초)",
   "gridPos": { "h": 11, "w": 10, "x": 7, "y": 1 },
   "targets": [
    { "expr": "node_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "인스턴스 별 평균 CPU 사용",
   "type": "timeseries",
   "description": "5분 동안 각 인스턴스의 초당 CPU 사용 시간을 측정하여, 인스턴스별 평균 CPU 사용률을 계산",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg by (instance) (irate(process_cpu_seconds_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "평균 CPU 사용률",
   "type": "timeseries",
   "description": "평균 cpu 사용률 (1시간)\n20개의 스레드",
   "gridPos": { "h": 13, "w": 8, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory 사용량(%)",
   "type": "gauge",
   "description": "전체 메모리 중 사용 가능한 메모리를 제외한 부분(즉, 사용 중인 메모리)을 퍼센트로 나타냄",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "사용 가능한 메모리 (%)",
   "type": "stat",
   "description": "사용 가능한 메모리 확인",
   "gridPos": { "h": 12, "w": 7, "x": 7, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_Active_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "1초당 세대 별 GC 평균 수행 횟수",
   "type": "timeseries",
   "description": "1분 동안의 GC 수집 증가량을 기준으로 초당 평균 GC 수집 횟수를 보여줌",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(dotnet_collection_count_total[1m])",
     "legendFormat": "[{{job}}] GC Gen {{generation}}"
    }
   ]
  },
  {
   "title": "GC 수행 횟수",
   "type": "timeseries",
   "description": "애플리케이션 별 Garbage Collection 총 수행 횟수 (세대별)",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 39 },
   "targets": [
    {
     "expr": "dotnet_collection_count_total{job=\"gameserver\"}",
     "legendFormat": "[{{job}}] GC Gen {{generation}}"
    },
    {
     "expr": "dotnet_collection_count_total{job=\"hiveserver\"}",
     "legendFormat": "[{{job}}] GC Gen {{generation}}"
    },
    {
     "expr": "dotnet_collection_count_total{job=\"matchserver\"}",
     "legendFormat": "[{{job}}] GC Gen {{generation}}"
    }
   ]
  },
  { "title": "HTTP & Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "HTTP 요청 평균 개수",
   "type": "timeseries",
   "description": "1분간 1초마다 들어온 HTTP 요청 평균 개수",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 요청 평균 처리 시간(초)",
   "type": "timeseries",
   "description": "최근 5분간 엔드포인트 별 HTTP 요청 평균 처리 시간(초)",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 51 },
   "targets": [
    {
     "expr": "avg by (endpoint) (rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login 요청 수",
   "type": "timeseries",
   "description": "Login API 누적 요청 수, API 초당 요청 수 (game & hive)",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "http_requests_received_total{endpoint=\"Login\"}",
     "legendFormat": "누적 요청 수"
    },
    {
     "expr": "rate(http_requests_received_total{endpoint=\"Login\"}[1m])",
     "legendFormat": "초당 요청 수"
    }
   ]
  },
  {
   "title": "네트워크 사용률",
   "type": "timeseries",
   "description": "네트워크 전송/수신 속도",
   "gridPos": { "h": 12, "w": 8, "x": 9, "y": 62 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[5m]) * 8",
     "legendFormat": "network transmit"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[5m]) * 8",
     "legendFormat": "network recive"
    }
   ]
  }
 ]
}